// Random Number Guessing Game:
// Develop a program that generates a random number between 1 and 100.
//  Allow the user to guess the number and provide feedback on whether the guess is too high,
//   too low, or correct.
 
// program where the user has to guess a number generated by a program




let btn = document.getElementById("btn");

let display = document.getElementById("display");

let gameNum1 = Math.floor(Math.random() * 100);
console.log(gameNum1);



btn.addEventListener("click", function(){
    let game = document.getElementById("game").value;
    if(game> gameNum1) {
        display.innerHTML = `Your number is too high!`;
    }else if (game< gameNum1) {
        display.innerHTML = `Your number is too low!`;

    }else if(game == gameNum1) {
        display.innerHTML = `Your number is correct!`;
    }else {
        display.innerHTML = `error!`
    }
})







